project:
  type: website
  #output-dir: docs

margin-footer: | 
  "This website uses Quarto and its building components are available on https://github.com/arthurheim/Personal-Website"

website:
  title: "Arthur Heim"
  twitter-card: true 
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: fa-home
      - href: Career.qmd
        text: CV and contact informations
        icon: fa-home  
      - href: PhD/PhDPage.qmd
        text: PhD dissertation
      - href: ISAJE/IsajeMain.qmd
        text: Ongoing research
      # - href: Labour/Reliance.qmd
      #   text: Labour economics
      - href: Teachings/Teachings.qmd
        text: Teachings
      - href: Publications/Publications.qmd
        text: Publications
    tools:
      - icon: <i class="fas fa-envelope"></i> 
        href: mailto:heimarthur@gmail.com
      - icon: twitter
        href: https://x.com/HeimArthur
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/arthurheim/Personal-Website
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

