project:
  type: website
  #output-dir: docs

website:
  title: "Arthur Heim"
  twitter-card: true 
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: fa-home
      - href: Career.qmd
        text: CV and contact informations
        icon: fa-home  
      - href: PhD/PhDPage.qmd
        text: PhD dissertation
      - href: ISAJE/IsajeMain.qmd
        text: Early childhood
      - href: Labour/Reliance.qmd
        text: Labour economics
      - href: Teachings/Teachings.qmd
        text: Teachings
      - href: Publications/Publications.qmd
        text: Publications

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

