project:
  type: website
  #output-dir: docs

body-footer: | 
  "This website uses Quarto and its building components are available on https://github.com/arthurheim/Personal-Website"

website:
  title: "Arthur Heim"
  twitter-card: true 
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house-heart
      - href: CVContacts.qmd
        text: CV and contact
        icon: person-lines-fill  
 #     - href: PhD/PhDPage.qmd
  #      icon: mortarboard-fill
   #     text: PhD dissertation
      - text: Ongoing research
        icon: bar-chart-steps
        href: ISAJE/IsajeMain.qmd
      
      - href: Labour/Reliance.qmd
        text: Labour economics
      - href: Teachings/Teachings.qmd
        text: Teachings
        icon: clipboard2-data-fill
      - href: Publications/Publications.qmd
        text: Publications
        icon: journal-bookmark-fill
      - href: Publications/Music.qmd
        text: Music
        icon: music-note-beamed  
    tools:
      - icon: mailbox-flag
        href: mailto:heimarthur@gmail.com
      - icon: twitter
        href: https://x.com/HeimArthur
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/arthurheim/Personal-Website
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

