---
title: "Ongoing research"
---

**This webiste is currently being built and is regularly updated**

# The ISAJE Project

###### With [Julien Combe - École polytechnique](https://sites.google.com/site/combeju/home)

## Overview

The ISAJE project (Investissement Social dans l'Accueil du Jeune Enfant - Social Investment in Early Childhood) started in 2019. Its primary objective is to produce high-quality evidence on the causal effects of daycare access for parents, children, and society.

## Methodology

In collaboration with Julien Combe, Professor of Economics at École Polytechnique, we developed assignment mechanisms based on recent market design literature. These mechanisms offer:

-   Sound theoretical properties
-   Tractable random variations in assignment probabilities

## Implementation

From 2020 to 2024, we applied these mechanisms to assign daycare seats in:

-   Up to 9 large urban centers in France
-   Between 2 to 4 assignment rounds per location

## Project Evolution

The ISAJE project has expanded into a comprehensive program with three main focus areas:

1.  [**Market Design**:]{.underline} Theory and applications
2.  [**Public Policy Design**:]{.underline} Development and scaling of tools for fair and transparent automatic daycare assignment processes
3.  [**Public Policy Evaluation**:]{.underline} Measuring the effects of daycare access on parent and child outcomes, and evaluating the consequences of automated assignment procedures

```{=html}
<iframe class="pdf-viewer" src="/Publications/pdfs/RATM_Fr0624.pdf" style="width:100%; height:500px;" frameborder="0"></iframe>
```
# Policies to foster access to formal childcare

###### [With Laudine Carbuccia](https://www.sciencespo.fr/liepp/fr/users/laudinecarbuccia.html), [Carlo Barone](https://www.sciencespo.fr/osc/fr/node/1608.html) & [Coralie Chevalier](https://sites.google.com/site/coraliechevallier/)

Access to early childcare for low socioeconomic status (SES) families has the potential to mitigate socioeconomic inequalities. Yet, there is an SES-based gap in early childcare enrolment. While low-SES families would benefit the most from attending early childcare, they access early childcare the least. We study cognitive and behavioural barriers behind this access gap assessing the effectiveness of informational interventions and personalised administrative support in enhancing early childcare application and access for low-SES families through a multi-arm experiment. Results reveal that the information-only treatment had minimal impact. Combining information and personalised administrative support significantly bridges the SES-gap in early childcare applications for those who receive support. However, despite large impacts on application rates, we find limited impact on access rates for low-SES families. Our study provides key insights for policymakers aiming to promote equitable access to high-quality early childcare.

#### Draft available SOON

# Active labour market policies and poverty

### The *Reliance* experiment

**DETAILS COMMING SOON**

For now, enjoy these slides in French

```{=html}
<iframe class="pdf-viewer" src="/Publications/pdfs/GalitzineHeimLiepp0524.pdf" style="width:100%; height:500px;" frameborder="0"></iframe>
```
