---
title: "Investissement social et nouvelles formes de pauvreté"
subtitle: "Un résumé"
author: "Arthur Heim"
#bibliography: ../../Endline/BIB_HEIM.bib
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: true
format: pdf
bibliography: Bib_GenIntro.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message=FALSE, warning=FALSE,fig.width = 8,fig.height = 5,fig.pos = "H" #, 
#cache.lazy = FALSE)
)

library(pacman)
p_load(here)

```

# Introduction

Ce document synthéthise la thèse de doctorat intitulé "*Investissement social et nouvelles formes de pauvreté"* soutenue le 24 Avril 2024 à l'École d'économie de Paris. Elle s'intéresse en particulier au problème des inégalités d'accès aux modes d'accueils formels et aux politiques de lutte contre la pauvreté à destination des familles monoparentales. Ces travaux ont été menés sous la direction de Marc Gurgand et à la Caisse nationale des allocations familiales dans le cadre d'un contrat CIFRE entre 2019 et 2022, puis d'un CDI qui continue au delà de la soutenance.

## Cadre d'analyse et problématique

L'investissement social est une approche visant à reconfigurer l'intervention sociale et la protection sociale pour mieux accompagner les individus dans leurs trajectoires de vie[^1] en réponse à l'évolution des besoins sociaux: transformations de la famille avec l'accroissement des divorces et la diversification des formes de ménages ; transformations des relations sociales avec la baisse des grands collectifs d'actions, syndicats et clergés, les fortes aspirations à l'émancipation et la reconnaissance pour l'égalité des femmes, des personnes racisées, des personnes LGBTQIA+, etc; transformations de l'économie et des institutions avec la mondialisation, la construction européen, les progrès technologiques,...

Ces changements ont profondément perturbé les mécanismes traditionnels de l'État social et mis en lumière ses limites, engendrant une crise tripartite : financière, d'efficacité et de légitimité. Dans un contexte de contraintes budgétaires, la prise en charge des risques sociaux traditionnels tels que le chômage, la santé et les retraites devient de plus en plus problématique, tandis que les nouveaux risques ne sont que partiellement couverts : la pauvreté infantile, les difficultés d'insertion professionnelle des jeunes et des moins qualifiés, les défis liés à l'articulation entre vie familiale et vie professionnelle, ainsi que la perte d'autonomie. Les enjeux de soutenabilité ne se posent plus qu'en terme de dette publique et la gestion des conséquences de l'anthropocène mettent, davantage encore, les sociétés sous tension.

Dans le chapitre introductif, on

1)  Une révolution silencieuse ayant mené, générations après générations, davantage de femmes - et d’autres minorités - à accroître leurs compétences et niveaux de diplômes, dépassant les niveaux des hommes ;
2)  Des transformations du tissu économique augmentant la demande de travail qualifié offrant des débouchés pour les diplômés, mais réduisant la demande pour des emplois intermédiaires et peu qualifiés. Mondialisation etc favorisant l’accès à des biens et services à moindre coût pouvant libérer du temps, et des changements institutionnels favorisant la participation au marché du travail des femmes (temps partiels cdd etc) ;
3)  Un phénomène d’appariement assortatif positif où les femmes les plus dotées en capital humain se mettent en relation avec des partenaires aux normes plus égalitaires et plus impliqués dans l’éducation des enfants ;
4)  Mais face à une relative rareté d’hommes diplômés par rapport aux femmes, et des perspectives économiques de plus en plus sombre pour les hommes et les femmes les moins diplômées, les bénéfices d’une vie maritales sont moins élevés, la vulnérabilité économique et l’évolution des dynamiques de pouvoir au sein des foyers augmente les tensions dans les relations et favorise les séparations.
5)  Les hommes et les femmes les moins diplômés se retrouvent alors plus souvent en situation d’isolement, avec des perspectives d’emploi limités et une plus grande vulnérabilité économique, moins de chance de trouver un ou une partenaire de “qualité”, ou des relations plus fragiles notamment du fait de la vulnérabilité économique.
6)  Parmi les couples les plus éduqués, le mariage joue à la fois un rôle d’assurance en mutualisant une partie des ressources individuelles pour absorber les chocs économiques (période de chômage), et un puissant générateur d’épargne par des économies d’échelles dans la consommation, l’accès à des crédits favorisant l’accès à la propriété, alimentant le capital économique des membres du foyer et l’héritage à transmettre à leurs enfants.
7)  Au sein d’une génération, les inégalités de revenus, de consommation, de patrimoine net, de taux et qualité de l’emploi augmentent.
8)  Équipés d’un niveau plus élevé de ressources économiques et culturelles, et des préférences jointes pour l’éducation des enfants, les couples les plus dotés en capital humain investissent davantage dans l’éducation de leurs enfants que ceux moins éduqués et que les familles monoparentales, pour lesquels les contraintes de temps pèsent davantage.

Dans un chapitre introductif,

Les trois années qui ont précédé ce projet ont été consacré à l'investissement social dans une mission jointe entre France stratégie et la Cnaf, et c'est au cours de cette première vie professionnelle que ce projet s'est consolidé.

L'investissement social est une approche visant à reconfigurer l'intervention sociale et la protection sociale pour mieux accompagner les individus dans leurs trajectoires de vie[^2] en réponse à l'évolution des besoins sociaux. Cette approche met l'accent sur la nécessité d'intervenir en amont des situations, notamment dès la petite enfance, afin d'anticiper et de prévenir les risques. Il apparait dans une période où les modèles d'États providence sont bousculés par des mutations profondes des sociétés générant de nouveaux défis : transformations de la famille avec l'accroissement des divorces et la diversification des formes de ménages ; transformations des relations sociales avec la baisse des grands collectifs d'actions, syndicats et clergés, les fortes aspirations à l'émancipation et la reconnaissance pour l'égalité des femmes, des personnes racisées, des personnes LGBTQIA+, etc; transformations de l'économie et des institutions avec la mondialisation, la construction européen, les progrès technologiques,...

Ces changements ont profondément perturbé les mécanismes traditionnels de l'État social et mis en lumière ses limites, engendrant une crise tripartite : financière, d'efficacité et de légitimité. Dans un contexte de contraintes budgétaires, la prise en charge des risques sociaux traditionnels tels que le chômage, la santé et les retraites devient de plus en plus problématique, tandis que les nouveaux risques ne sont que partiellement couverts : la pauvreté infantile, les difficultés d'insertion professionnelle des jeunes et des moins qualifiés, les défis liés à l'articulation entre vie familiale et vie professionnelle, ainsi que la perte d'autonomie. Les enjeux de soutenabilité ne se posent plus qu'en terme de dette publique et la gestion des conséquences de l'anthropocène mettent, davantage encore, les sociétés sous tension.

## Problématique

Alors que l'investissement social occupe une place de choix dans la conception des politiques publiques dans la plupart des pays de l'OCDE et revêt une importance centrale dans d'autres domaines des sciences sociales, cette notion reste relativement marginale en économie. Néanmoins, dans cette thèse, je l'adopte comme cadre général pour concevoir et évaluer les politiques de la petite enfance ainsi que les politiques actives du marché du travail destinées aux familles monoparentales. Dans les deux cas, l'investissement social fournit des objectifs politiques ainsi que des critères normatifs permettant de juger les effets souhaités, les externalités et d'évaluer le succès ou l'échec des politiques mises en œuvre. Pour ce faire, je concentre mon analyse sur les trois principaux récits du paradigme de l'investissement social :

1)  Investir dans la petite enfance pour réduire les inégalités et rompre le cycle intergénérationnel de la pauvreté ;
2)  L'activation comme moyen de favoriser l'emploi et de réduire la pauvreté ;
3)  Les suppléments de revenu pour rendre le travail rémunérateur.

En France, la littérature sur les effets des investissements sociaux dans la petite enfance ou dans les politiques actives du marché du travail est relativement limitée [@bono2021]. En particulier, il n'existe pas de preuves expérimentales des effets de l'accès à la garde d'enfants ou des programmes de transition du bien-être au travail pour les familles monoparentales. Cette thèse vise à combler cette lacune en proposant une approche expérimentale pour les deux cas. Ma principale contribution réside dans l'utilisation de méthodes économiques de pointe pour répondre à la question de recherche suivante :

-   **Comment les politiques d'investissement social affectent-elles la dynamique de la pauvreté en France ?**

Chaque chapitre aborde un puzzle spécifique :

-   **Puzzle n°1** : Pour que les politiques petite enfance puissent atteindre les objectifs qui leurs sont assignés, il est nécessaire de s’assurer que ceux qui peuvent en bénéficier le plus y ont accès. Dans le cas des crèches, la rareté impose de faire des choix, et chaque choix implique un coût d’opportunité.
    -   *Dans quelle mesure est-il possible de mettre en place un mécanisme optimal d'attribution des places en crèche ? Quelles sont les conséquences des différents choix de conception ?*
-   **Puzzle n°2** : Parmi les populations les plus vulnérables on trouve une part importante de familles monoparentales bénéficiaires de minima-sociaux. Une solution proposée dans la droite ligne des politiques d’activation est l’accompagnement vers l’emploi.
    -   *Les programmes d’accompagnement global vers l’emploi permettent-ils aux familles monoparentales de sortir de la pauvreté par l’activité ?*
-   **Puzzle n°3** : le système socio-fiscal français – particulièrement les aides des CAF – est complexe, peu lisible et les incitations très différentes suivant les configurations familiales
    -   *Comment réagissent les mamans-solo pauvres aux incitations du système socio-fiscal français ?*

# Rage against the matching

Ce chapitre est co-signé avec Julien Combe, professeur d'économie à l'école polytechnique et porte sur les mécanismes d'affectations des places en crèche et une analyse des inégalités sociales d'accès liées au fonctionnement des commissions d'attribution. Dans cet article, nous considérons l'accès à la crèche comme un problème d'appariement où la demande rencontre l'offre grâce à un mécanisme d'attribution centralisé organisé par les autorités locales.

Nos principales contributions sont doubles. Premièrement, nous fournissons des modèles et des algorithmes pour différentes versions du problème d'attribution de crèche avec des propriétés bien comprises. Les applications fournissent aux décideurs de nouveaux outils pour attribuer aux parents leur crèche préférée suivant des priorités avec diversité et des contraintes multidimensionnelles. Deuxièmement, nous utilisons deux études de cas pour analyser les effets des contraintes de diversité, des priorités et des mécanismes d'attribution sur les inégalités dans l'accès en crèche selon différentes dimensions.

Nous avons remarqué que l'organisation des commissions d'affectation présentait certaines caractéristiques familières. En particulier:

i)  les affectations sont centralisées par les collectivités locales,
ii) les parents s'inscrivent tout au long de l'année et soumettent leurs préférences pour les crèches qu'elles préfèrent,
iii) la plupart des offres sont disponibles en septembre lorsque les enfants plus âgés passent à l'école maternelle, et
iv) les collectivités locales organisent un comité d'attribution principal au printemps pour attribuer ces places.

Le problème d'attribution des places en crèche est donc très similaire au problème de choix d'école pour lesquels des solutions bien définies et de nombreuses applications réussies existent déjà [@abdulkadiroglu2003].

Dans cette littérature, l'objectif est généralement de définir des appariements *stables* et des algorithmes pour les trouver. La *stabilité* est une propriété que nous voulons qu'un appariement respecte afin de justifier aux parents *pourquoi* l'attribution est ainsi. La motivation théorique pour se concentrer sur des ensembles d'appariements stables est que si le résultat du marché est instable, il y a des agents ou des paires d'agents qui ont l'incitation à contourner l'appariement \[\@roth2008\]. Dans certains cas, les chercheurs et/ou les décideurs utilisent déjà les résultats de la littérature sur la conception des marchés (*Market design*) pour fournir des mécanismes d'attribution des places en crèche.

Le terme *marché* a une charge politique importante, mais pas pour tout le monde et pas de la même manière. Pour certaines personnes, le terme de *marché* n'évoque rien de particulier, c'est un terme *inerte* qui désigne, notamment, un lieu où l'on fait des achats. Pour d'autres, il évoque le vocabulaire des *néolibéraux* et sa simple prononciation suscite une forme de défiance envers celui ou celle qui l'emploie. Pour des chercheurs en économie, le terme *marché* a un sens bien particulier. De plus, les *marchés* que nous définissons équilibrent offre et demande à partir d'un *algorithme*. Là aussi, la polysémie du terme et les enjeux politiques associés sont grands.

### Market design et économie politique

Notre travail ne consiste pas à proposer une mise à jour des logiciels des directions petite enfance des territoires -- même si cela peut passer par là -- mais à concevoir des *places de marché*. Si nous utilisons ces termes, c'est parce que nous nous intéressons aux *transactions* que ce système permet d'organiser et à ce que la *société* tire d'une telle organisation. Les économistes[^3] ont tendance à adopter des définitions assez larges de ce qui constitue une transaction et (donc) un marché [@satz2010]. Des précisions s'imposent.

En bref, un marché est une institution qui facilite les transactions. Il peut être formel ou informel, conçu, encadré, physique, virtuel, utilisant un système de prix ou non... Un point important est que les caractéristiques du marché affectent qui négocie, ce qui est négocié et les termes de ces transactions [@li2017]. Ainsi, les *places de marché* se présentent sous de nombreuses formes et ne sont pas uniquement, ni même principalement, des marchés de biens et services dont la seule fonction est la découverte des prix. \@roth2018 définit les places de marché comme[^4] "*l'infrastructure, les règles et les coutumes par lesquelles les informations sont échangées et les transactions effectuées, qui peuvent être des parties relativement petites de grands marchés. Les participants peuvent avoir de vastes ensembles de stratégies, c'est-à-dire de nombreuses options à leur disposition au-delà de celles disponibles sur une place de marché particulière*".

Sur de nombreux marchés, nous nous soucions de savoir avec qui nous échangeons. Dans ces configurations, nous ne pouvons pas nous contenter de choisir ce que nous voulons, même si nous en avons les moyens : nous devons aussi être choisis. Le marché des modes d’accueils fait partie de ces marchés d’appariement (*matching markets*). Il existe des lieux d'inscriptions centralisés (les guichets uniques) donnant accès à une place de marché : les commissions d'admission des modes d'accueil (CAMA). Ces dernières sont en charge de l'appariement entre les offres de différents gestionnaires et les demandes des parents. Bien qu'elles proposent principalement des places en établissements d'accueil collectif du jeune enfant (EAJE) gérés, de près ou de loin, par le territoire, certaines proposent aussi des places dans des crèches associatives, des crèches familiales, des crèches d'entreprises, hospitalières ou universitaires,... En outre, cette place de marché n'est pas l'unique lieu des transactions pour les modes d'accueils. Les parents ont également d'autres options. Ils peuvent passer un contrat privé avec une assistante maternelle ou une crèche privée, s'occuper eux-mêmes de leurs enfants, définir une organisation repartissant la garde entre eux, des membres de leur famille ou d'autres liens sociaux, etc.

Pour un marché donné et une définition de la stabilité, une appariement stable peut ne pas exister, ou il peut y en avoir plusieurs. Il existe modèles, algorithmes et façon de poser le problème qui peuvent produire des \emph{résultats} très différents, c'est-à-dire en termes de distribution des affectations, ainsi qu'un ensemble de \emph{conséquences}. Comme le souligne @li2017, une conséquence est plus riche qu'un résultat, c'est une "\emph{description des effets du marché sur le monde}". Il s'agit alors de peser et de résoudre les compromis entre différents objectifs et contraintes. Les modèles et la théorie aident à clarifier quels sont (certains de) ces compromis.

D'expérience, de nombreuses institutions locales collectent les préférences sur les jours de la semaine et attribuent les dossiers en conséquence[^5]. Ce simple changement dans la manière dont les préférences sont collectées a des conséquences importantes sur la définition de la stabilité.

Les décideurs sont familiers avec les détails de leur environnement, et pourtant ils ne savent souvent pas comment formuler leurs objectifs en termes précis ou réalisent qu'ils sont conflictuels. Cependant, la théorie aide à fournir "*des orientations sans prescrire une théorie éthique entière*" [@li2017].

De nombreux objectifs politiques dépendent de ce qui est réalisable. Par exemple, un décideur politique pourrait penser qu'il est moralement obligatoire de mettre en place un système qui est optimal au sens de Pareto[^6] pour les familles et respecte les priorités. Mais cela n'est pas possible [@abdulkadiroglu2003] donc cela ne peut pas être une contrainte morale ou politique. Lorsque l'attribution se fait en allouant des places sur les jours de la semaine, les développements récents sur l'appariement avec des contraintes multidimensionnelles pour la garde d'enfants [@kamada2023] et les relactions de réfugiés [@delacrétaz2023] fournissent différentes définitions de la stabilité et des algorithmes pour trouver des affectations stables avec d'autres propriétés souhaitables. Un résultat important de ces articles est qu'aucun algorithme ne peut respecter les priorités[^7] et ne pas laisser de places vides. Encore une fois, les deux ne peuvent pas être réalisés, donc cela ne peut pas être un objectif politique. Cette littérature récente fournit des solutions théoriques bien adaptées au problème d'attribution de places en crèche avec des contraintes multidimensionnelles.

Cependant, la mise en œuvre dans la vie réelle ajoute une autre couche de complexité. En effet, une autre caractéristique importante du système français est l'existence de contraintes de diversité dans toutes les structure et les procédures d'attribution. Les contraintes de diversité impliquent que les capacités au sein des crèches sont divisées en *groupes*, c'est-à-dire en ensembles de capacités avec des règles de priorité attachées aux *groupes*. Par exemple, certaines capacités seront réservées aux enfants de 6 à 12 mois uniquement, et d'autres aux enfants de 12 à 24 mois. Ces contraintes de diversité peuvent être *rigides* lorsque les groupes n'acceptent qu'un seul groupe, comme dans les exemples précédents. Parfois, les contraintes sont *flexibles* et définissent un ordre de préférence sur les groupes. Par exemple, un groupe peut accepter des enfants de 12 à 24 mois mais aussi des enfants plus âgés s'il y a suffisamment de capacité pour les accueillir. Alors que les formes les plus courantes de contraintes de diversité sont les groupes d'âge, les décideurs politiques et/ou les gestionnaires définissent de nombreuses autres formes de contraintes de diversité[^8].

## Principale contribution théorique

Ces contraintes de diversité jouent un rôle important dans le manque de transparence des procédures d'attribution de places en crèche. En effet, les commissions d'attribution ne trient pas simplement les dossiers par priorités dans une crèche, elles considèrent l'attribution au sein de groupes, dont les définitions varient à l'intérieur et entre les crèches, générant ainsi plus ou moins de concurrence entre les groupes et donc des variations dans les probabilités d'attribution. Dans un appariement donné, il peut y avoir des enfants avec des scores de priorité bas attribués à une crèche que les parents ayant une priorité plus élevée voulaient mais ont été rejetés. Ainsi, la notion de stabilité ne peut pas être uniquement basée sur les scores de priorité, elle doit prendre en compte la répartition des capacités en groupes et les priorités à l'intérieur et entre les groupes.

Fournir une notion de stabilité dans un cas avec des contraintes multidimensionnelles et de diversité est donc à la fois pertinent sur le plan théorique et nécessaire pour assurer la transparence et le respect du processus.

Notre résultat principal pose la définition d'une places de marché pour l'attribution des places en crèche (DAM) comme trois éléments que les décideurs doivent choisir :

1)  Une version du problème : qu'ils considèrent les demandes avec des jours spécifiques ou non ;
2)  Une partition des capacités en *groupes*, c'est-à-dire un ensemble de capacités avec des règles de priorité attachées dans chaque crèche pour définir les contraintes de diversité ;
3)  Une définition de *l'équité* : avec des scores de priorité et si les mécanismes doivent éliminer l'envie justifiée, tolérer certaines petites déviations ou considérer uniquement les demandes initialement réalisables.

En nous appuyant sur le travail de @ehlers2014 dans un cas sans attribution de jours spécifiques, @kamada2023 et @delacrétaz2023 dans un cas avec attribution de jours spécifiques, nous proposons des notions de stabilité pour différentes versions du problème d'attribution de places en crèche avec des contraintes de diversité.

Notre principal résultat énonce ensuite que pour chaque DAM, nous pouvons trouver l'attribution équitable optimale unique pour les familles (SOFA), qui respecte la définition *choisie* de l'absence d'envie. Nous fournissons également une définition supplémentaire de stabilité sur les *demandes initialement réalisables*. À partir d'un SOFA avec toutes les demandes, nous montrons dans un autre théorème que supprimer les demandes initialement irréalisables est préférable pour tous les parents et donc, améliore au sens de Pareto l'attribution qu'ils reçoivent. Dit autrement, les personnes avec des scores élevées dont le voeu ne peut être réalisé dès le départ en raison d'un manque de capacité génèrent des externalités négatives sur les dossiers moins prioritaires qui pourraient être affectés. En retirant ces voeux, les personnes à qui on retire les voeux ne sont pas pénalisés puisque ces voeux ne pouvaient de toute façon être satisfaits ; mais les retirer permet à d'autres familles d'avoir parfois un meilleur choix. En pratique, ce théorème s'avère le plus utile dans les seconds tours où il y a beaucoup plus de jours vides dans les groupes.

## Implication pour les politiques publiques

Une fois que les décideurs politiques définissent leur DAM, les procédures proposées offrent plusieurs avantages distincts par rapport aux pratiques actuelles:

1)  Ces outils informatiques peuvent rapidement traiter un grand nombre de demandes, ce qui permet de gagner du temps pour ceux impliqués dans l'organisation et la participation aux commissions d'attribution.
2)  Nos modèles clarifient ce qui peut être fait et ce qui ne peut pas l'être, ainsi que les compromis de chaque mécanisme d'attribution. D'un point de vue normatif, ils garantissent des affectations *justes* au sens où ils éliminent les *envies justifiées* sur la base d'une définition claire et choisie. Les décideurs politiques choisissent s'ils veulent respecter strictement les priorités ou accueillir davantage d'enfants en autorisant une adaptation faible et/ou en ne tenant compte que des demandes initialement réalisables.
3)  Toutes les décisions d'attribution sont traçables et peuvent être expliquées à chaque famille. Pour chaque attribution, nous fournissons un tableau pour chaque crèche qui justifie chaque décision. Une transparence totale est possible, si les décideurs politiques souhaitent aller vers cette direction.
4)  En garantissant que les priorités sont toujours respectées et individuellement justifiables, ils peuvent créer un bien public: ces mécanismets assurent une forme de *justice procédurale* et peuvent déplacer les préoccupations éthiques et de justice vers la *justice distributive*. Puisque les priorités sont toujours respectées, la société peut débattre de ce qui constitue des inégalités justes.
5)  Les décideurs politiques peuvent définir des distributions d'affectation cibles en choisissant les parts de places qu'ils veulent attribuer à certains groupes. Nos modèles sont suffisamment flexibles pour prendre en compte de nombreuses contraintes. En particulier, la définition de quotas de diversité (flexibles) est un outil puissant pour garantir que l'affectation satisfait certaines exigences de distribution. Sans notre procédure, ce type d'objectifs politiques est très difficile à atteindre. Ou du moins, difficile à justifier.
6)  Ces outils peuvent également être utilisés pour simuler les effets de la modification de certains paramètres et informer les décideurs politiques en utilisant des scénarios *et si*.

[^1]: Voir notamment le livre @avenel2017 reprenant les ensignements d'un cycle de séminaire sur la définition d'une stratégie d'investissement sociale pour la France.

[^2]: Voir notamment le livre @avenel2017 reprenant les ensignements d'un cycle de séminaire sur la définition d'une stratégie d'investissement sociale pour la France.

[^3]: dont nous faisons partie.

[^4]: "*infrastructure, rules, and customs through which information is exchanged and transactions are made \[that\] can be relatively small parts of large markets. Participants may have large strategy sets, i.e., many options available to them beyond those available in any particular marketplace*"

[^5]: En l'absence de jours spécifiques, un enfant occupe un siège, qui est un bien indivisible et unitaire. Cependant, dans des contextes avec des jours spécifiques, un enfant peut prendre certains jours et le reste peut être attribué à un autre avec des préférences complémentaires, ou non. Une place n'est plus indivisible et unitaire.

[^6]: Dans ce contexte, une affectation Pareto efficace implique que la distribution des places en crèche ne peut pas être améliorée d'une manière qui bénéficie à au moins un participant sans nuire à un autre participant.

[^7]: avec différentes définitions dans les deux articles.

[^8]: par exemple, pour les parents dont les horaires varient au fil des mois ou avec des horaires de travail décalés, ceux qui sont dans une politique active du marché du travail etc.
